# Analytics RESTBase config

info:
  name: analytics_restbase


templates:

  wmf-analytics-1.0.0: &wp/analytics/1.0.0
    swagger: '2.0'
    # swagger options, overriding the shared ones from the merged specs (?)
    info:
      version: 1.0.0-beta
      title: Wikimedia Analytics REST API
      description: >
          This API aims to provide coherent and low-latency access to
          Wikimedia analytics content. It is currently in beta testing, so
          things aren't completely locked down yet. Each entry point has
          explicit stability markers to inform you about development status
          and change policy, according to [our API version
          policy](https://www.mediawiki.org/wiki/API_versioning).

          ### High-volume access
            - Don't perform more than 500 requests/s to this API.
            - Set a unique `User-Agent` header that allows us to contact you
              quickly.  Email addresses or URLs of contact pages work well.
            - Consider using our [dumps](http://dumps.wikimedia.org/) once they
              become available.

      termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
      contact:
        name: the Wikimedia Analytics team
        url: http://mediawiki.org/wiki/Analytics
      license:
        name: Apache2
        url: http://www.apache.org/licenses/LICENSE-2.0
    x-subspecs:
      - mediawiki/v1/analytics

  wmf-sys-1.0.0: &wp/sys/1.0.0
    info:
      title: Default MediaWiki sys API module
      version: 1.0.0
    paths:
      /{module:table}: &wp/sys/table # Can use this anchor to share the table
        x-modules:
          # There can be multiple modules too per stanza, as long as the
          # exported symbols don't conflict. The operationIds from the spec
          # will be resolved against all of the modules.
          - name: restbase-mod-table-cassandra
            version: 1.0.0
            type: npm
            options: # Passed to the module constructor
              conf:
                hosts: [localhost]
                keyspace: system
                username: cassandra
                password: cassandra
                defaultConsistency: one # or 'one' for single-node testing
                storage_groups:
                  - name: test.group.local
                    domains:
                      - /test\..*\.org$/
                      - /test\.local$/
                  - name: default.group.local
                    domains: /./

      /{module:pageviews}:
              x-modules:
                  - name: pageviews
                    version: 1.0.0
                    type: file

  wp-default-1.0.0: &wp/default/1.0.0
    x-subspecs:
      - paths:
          /{api:v1}:
            x-subspec: *wp/analytics/1.0.0
      - paths:
          /{api:sys}:
            x-subspec: *wp/sys/1.0.0


spec: &spec
  title: "The RESTBase root"
  # Some more general RESTBase info
  paths:
    /{domain:analytics.wikimedia.org}: *wp/default/1.0.0


services:
  - name: restbase
    module: ./lib/server
    conf:
      port: 7231
      spec: *spec
      salt: secret
      default_page_size: 250

logging:
  name: restbase
  level: info
  #streams:
  ## XXX: Use gelf-stream -> logstash
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  #type: txstatsd
  #host: localhost
  #port: 8125
