# Simple test spec

swagger: 2.0

paths:
  /{module:pageviews}/stats/{project}/{agent}/{article}/{granularity}/{start}/{end}:
    get:
      x-backend-request:
        uri: /{domain}/sys/pageviews/stats/{project}/{agent}/{article}/{granularity}/{start}/{end}
      x-monitor: false
  /{module:pageviews}/insert:
    get:
      x-backend-request:
        uri: /{domain}/sys/pageviews/insert
      x-monitor: false
